//
//  Strings.swift
//  Hotel info
//
//  Created by Сергей Золотухин on 08.09.2023.
//

enum Strings {
    static let chooseAppartment = "К выбору номера"
    static let comfort = "Удобства"
    static let needed = "Самое необходимое"
    static let included = "Что включено"
    static let nonIncluded = "Что не включено"
    static let hotel = "Отель"
    static let hotelName = "Steigenberger Makadi"
    static let aboutHotel = "Об отеле"
    static let appartmentDescription = "Подробнее о номере"
    static let chooseRoom = "Выбрать номер"
    static let booking = "Бронирование"
    static let firstTourist = "Первый турист"
    static let secondTourist = "Второй турист"
    static let thirdTourist = "Третий турист"
    static let fourthTourist = "Четвертый турист"
    static let flyFrom = "Вылет из"
    static let countryCity = "Страна, город"
    static let dates = "Даты"
    static let numberOfNights = "Кол-во ночей"
    static let number = "Номер"
    static let nutrition = "Питание"
    static let buyerInfo = "Информация о покупателе"
    static let phoneNumber = "Номер телефона"
    static let phoneNUmberPlaceholder = "+7 (951) 555-99-00"
    static let email = "Почта"
    static let emailPlaceholder = "examplemail.000@mail.ru"
    static let paidDescription = "Эти данные никому не передаются. После оплаты мы вышли чек на указанный вами номер и почту"
    static let phoneMask = "+7 (***) ***-**-**"
    static let name = "Имя"
    static let namePlaceholder = "Иван"
    static let surname = "Фамилия"
    static let surnamePlaceholder = "Иванов"
    static let birthsday = "Дата рождения"
    static let citizen = "Гражданство"
    static let passportNumber = "Номер загранпаспорта"
    static let passportValidity = "Срок действия загранпаспорта"
    static let addTourist = "Добавить туриста"
    static let tour = "Тур"
    static let fuel = "Топливный сбор"
    static let service = "Сервисный сбор"
    static let toPaid = "К оплате"
    static let gotToWork = "Ваш заказ принят в работу"
    static let superTitle = "Супер!"
    static let paid = "Заказ оплачен"
}
